### ISSUE TITLE
cShowItemTooltipEx 3

### ISSUE THREAD

**Issue by ghost** [teralove/cross-server-tooltip#1]
I only see a version 2 in Meishu's tera-data. Do you have an updated def?

**Comment by teralove** [comment]
Oh yea. I completely forgot that I updated the def. I'll let you know when it has been committed to tera-data.

**Comment by ghost** [comment]
Just merged the PR to tera-data. There were also some updates to KR sysmsg so I might be able to convince pinkie pie to release a new proxy bundle with the new def.

**Comment by teralove** [comment]
Thanks
